include ":attributes:attributes";
include ":disguise:disguise";
include ":charactercreation:createchar";

const aiglaText := "Os Aiglanos são um povo astuto e inclusivo, conhecido por sua capital Aquileia. Sua bandeira apresenta uma águia dourada em um fundo vermelho, simbolizando a seleção dos capazes. Eles são um povo mestiço, com variação de tom de pele, altura e tipo de cabelo. São disciplinados, valorizam a história e fazem do exercício físico um hábito.
Historicamente, os Aiglanos prosperaram apesar dos desafios, aprendendo com suas fraquezas e remodelando-se. Passaram de um pequeno vilarejo para uma República, com um sistema político fechado. A ascensão do Imperador Crassus trouxe um período de bonança, com reformas militares e de governo que expandiram o poder do império.
A religião Aiglana é flexível, absorvendo divindades dos povos conquistados através do ritual de evocatio. Os costumes incluem uma nobreza intocável, lealdade à legião e pagamento dos legionários durante campanhas.
Em resumo, os Aiglanos são um povo resiliente e adaptável, com uma história marcada por conquistas militares e uma cultura diversificada.";

const lesteText := "Os Povos do Leste são caracterizados por sua extensa terra, liderada pela Dinastia Huang, com uma cultura diversificada apesar da unificação sob uma única dinastia. O gentílico varia de acordo com a classe social, com destaque para os kamis, heimins e heinins. A pele clara a amarelada e olhos com palpebras puxadas são características comuns.
A história remonta à unificação sob a Dinastia Huang, que governa há milênios, marcada por conflitos e unificações. A religião central é o culto ao Deus-dragão, que permeia todas as camadas da sociedade, especialmente através dos monges e samurais, que seguem uma rígida disciplina e código de honra.
A ascensão do atual Imperador, Fan Huang, marcou uma mudança drástica na dinastia, com a extinção do culto ao dragão e a ampliação da Grande Muralha, levando ao surgimento da 'Fúria do Dragão' e uma onda de refugiados.
A religião Kai é central na vida dos povos do Leste, baseada na lealdade absoluta ao Imperador como mensageiro do Deus-dragão. A história mitológica envolve a transformação do primeiro imperador em um dragão dourado.
Curiosidades incluem a simplicidade dos monges, a saga dos ronins, a importância do peixe na dieta e a cremação como ritual funerário. Rumores sobre uma ordem assassina chamada sicários ainda pairam sobre a região.
A fisionomia varia, mas os povos do Leste são geralmente de estatura média, com pele clara a amarelada e cabelos escuros. Suas vantagens raciais incluem habilidades de combate e a habilidade de se tornarem monges e samurais. A língua comum é Haiei.";

const harolothText := "Os Drows são uma raça de elfos negros com pele escura e olhos variados, mas com íris claras, muitas vezes brilhantes na escuridão. São de estatura média, com as fêmeas geralmente mais baixas do que os machos. Seu estilo de combate privilegia emboscadas e ataques sorrateiros, evitando confrontos diretos.
A origem dos Drows é envolta em mistério, mas acredita-se que tenham surgido nos subterrâneos do continente. Sua sociedade é marcada pelo conflito interno e pela busca pelo raro minério Illyra, fonte de poder e riqueza para suas casas.
A religião dos Drows gira em torno de Idrith, uma deusa sacrificada pelo bem-estar de todos. Sua sociedade é baseada no medo, com o Clero de Idrith, a Liga de Comerciantes e o Braço Armado sendo as principais instituições. A nobreza drow é dividida em castas, onde o poder e a influência são os principais critérios de avaliação.
Curiosidades sobre os Drows incluem sua falta de afeto infantil, a importância das fêmeas na sociedade, sua apreciação por arte e música, orgulho racial e conhecimento da língua comum. Embora possam agir de forma imprevisível individualmente, os Drows são impiedosos e implacáveis em sua busca por poder quando em sociedade.";

const bjorskaText := "Os Björske são um povo tradicional do norte do continente de Eora, conhecidos por sua pele alva e cabelos que variam do preto ao loiro e ruivo. São orgulhosos, valentes e generosos, transmitindo suas tradições oralmente, reunindo-se em torno de fogueiras para cultuar seus deuses com danças, carne de caça e hidromel.
Sua história remonta a tribos antigas que enfrentaram grande fome e ataques dos Aiglanos, sendo lideradas por Brago, um líder astuto e forte. Ele uniu as tribos, lutou contra os invasores e estabeleceu o reinado dos Björske, sendo adorado mesmo após sua morte.
A religião dos Björske, chamada Haulleuad, é centrada no culto ao Sol e à Lua, representando força, proteção e fertilidade. O pai, Duw, o Deus Sol, e a mãe, Lleuad, a Lua, são adorados em festivais e rituais que celebram a natureza e os ciclos da vida.
Os Björske são guerreiros habilidosos, especialmente montados, utilizando cavalaria e formação de escudos em combate. São conhecidos por sua fúria e tradição, valorizando a força e a fertilidade. Sua cultura valoriza a oralidade e a música, enquanto sua língua nativa é o Björ e também falam o Comum.";

const alurielText := "Os elfos são uma raça antiga e majestosa, abençoados por Alora Larethian, a Luz Eterna. Com vida longa, chegando até 300 anos e ocasionalmente ultrapassando 700 anos, os elfos possuem uma perspectiva única e contemplativa sobre a vida e o mundo ao seu redor. Eles são esbeltos e ágeis, com pele clara, cabelos e olhos predominantemente claros, refletindo sua conexão com a natureza e a magia.
A sociedade élfica é profundamente ligada à natureza e às tradições. Eles veem a terra como uma extensão de si mesmos e se dedicam a protegê-la. Mestres na criação de artefatos sustentáveis, os elfos utilizam técnicas que não prejudicam o meio ambiente. Suas histórias e conhecimentos são preservados através da poesia e celebrações sazonais, destacando a reverência pelas tradições.
Elfos são contemplativos, meditando e refletindo antes de tomar decisões importantes. Essa característica os torna resistentes a mudanças, especialmente aquelas que perturbam a natureza. A religião dos elfos gira em torno de Alora Larethian, deusa da beleza e da magia, cuja presença é celebrada com festas e canções. A bênção de Alora confere aos elfos grande habilidade em magia, facilitando seu uso e tornando-os excelentes magos.
Os elfos mantêm uma rivalidade histórica com os anões devido à sua aversão à tecnologia. Acreditam que a pureza de suas obras, inspiradas pela natureza, supera qualquer criação tecnológica. Essa rivalidade se reflete em sua atitude reservada e, por vezes, hostil em relação aos avanços tecnológicos e aos estrangeiros.";

const polkineaText := "Os Polski são um povo diverso e tranquilo, com uma estatura média de 90 centímetros e um corpo rechonchudo que varia de 20 a 30 quilogramas. Sua pele bronzeada pode variar de tons mais escuros a mais claros, e traços distintos podem indicar a linhagem familiar. Eles valorizam o conforto e a simplicidade em suas vestimentas e casas, mas têm orgulho de se vestirem bem.
Os Polski cultivam as terras de Colhesol há centenas de anos, preferindo manter-se à parte dos problemas dos povos maiores. São conhecidos por seu amor pela comida, fumo e bebidas, bem como pela paz e tranquilidade da vida no campo. Suas habilidades em cultivo e culinária são notáveis, e eles desenvolveram um comércio de especiarias e condimentos.
Divididos em três grupos principais - Pérvalhos, Cascalvas e Encostarvores - os Polski têm laços familiares fortes e um sistema político baseado em decisões comunitárias. São conhecidos por sua capacidade de passar despercebidos e por conquistar a amizade dos outros.
Os Polski não se preocupam muito com posses materiais e valorizam a hospitalidade e a simplicidade. Seus costumes incluem compartilhar ferramentas e lidar com limites e privacidade de maneira única. São habilidosos em fala e canto, apreciando a arte do improviso.
Em resumo, os Polski são criaturas simples que valorizam o conforto, a boa comida e a calmaria da vida no campo, além de serem ótimos agricultores e, em alguns casos, aventureiros.";

const baduranText := "Os Anões são uma raça distintiva, reconhecível por suas longas barbas adornadas e estatura baixa, mas robusta. Com uma cultura profundamente enraizada na forja e na tecnologia, eles habitam regiões montanhosas e possuem uma sociedade organizada, com líderes como o 'Pai' e a 'Mãe'. Sua relação com outras raças é marcada por um misto de hospitalidade e irritabilidade, especialmente com os elfos, com os quais têm uma rivalidade histórica.
Vestidos com suas melhores armaduras e tecidos, os Anões buscam demonstrar sua destreza e riqueza por meio de suas vestimentas. São inventivos em suas forjas e valorizam o trabalho árduo, considerando a terra como uma arte insuperável. A forja desempenha um papel crucial em sua identidade, transmitindo tradições e ensinamentos aos mais jovens.
Na esfera religiosa, os Anões adoram um poderoso deus criador e reverenciam seus antepassados, como Galgrumir, Killi e Thorgrim, conhecidos por suas grandes realizações. Além disso, possuem um conjunto de vantagens raciais, como resistência a magias e bônus em HP e stamina, refletindo sua constituição robusta e vontade inabalável.
Sua fortaleza, Khron Kaz'ad, é uma grandiosa construção subterrânea repleta de tesouros e minas profundas, refletindo sua habilidade em trabalhar com o ambiente montanhoso. Os Anões são tradicionalistas, leais e valorizam o trabalho árduo, características que permeiam sua cultura e comportamento.";

const gulthrakText := "Os Orcs são uma raça de humanoides guerreiros, mais altos e fortes que os humanos, com pele calejada variando do vermelho ao verde. Sua história remonta ao Deserto da Perdição, onde enfrentaram desafios extremos para sobreviver, incluindo batalhas contra criaturas perigosas chamadas Aklats. Seu modo de vida nômade foi marcado por um culto à força e à sobrevivência.
A religião dos Orcs gira em torno de Adar Kor Doom, representando os elementos areia, água e sangue, que sustentam o ciclo de vida e fertilidade. Os Xamãs são responsáveis por preservar esses ensinamentos e tradições.
Curiosidades sobre os Orcs incluem seu uso de armaduras feitas de couro, ossos e materiais encontrados, sua reverência pelas chuvas sagradas do deserto e a igualdade de gênero em sua sociedade, onde tanto machos quanto fêmeas guerreiam e lideram tribos.
Na adolescência, os Orcs são submetidos a ritos de passagem no deserto e enfrentam os perigos das dunas. A presença de forasteiros no deserto era comum, mas os Orcs geralmente não forneciam ajuda, exceto em situações de perigo contra os Aklats.
Alguns Orcs vivem sem tribo, considerados perigosos por não seguirem as tradições. Eles se esforçam para resolver conflitos na Arena de Sangue, mesmo fora do deserto, mantendo um código de honra entre eles.";

const veneratioText := "A Veneratio é a religião dos Aiglanos, caracterizada pela adoração a uma variedade de divindades, incluindo o Demiurgo, o criador do universo. Os Aiglanos praticam rituais de adoração, fazem oferendas e honram os templos das divindades para garantir proteção e prosperidade. Eles valorizam a tradição, a história e o serviço à comunidade, 'enquanto mantêm uma atitude inclusiva em relação às crenças dos outros povos. Para ser fiel à sua religião, os personagens devem demonstrar devoção às divindades, respeitar as tradições, servir à comunidade e aceitar a diversidade religiosa.";
const loreText := "Os elfos, conhecidos como Quendi, são um povo antigo e sábio, intrinsecamente ligado à natureza e à magia. Sua sociedade é marcada pela reverência à deusa Alora Larethian, a Luz Eterna, que os abençoou com a magia e os uniu em tempos de discórdia. Os elfos vivem em harmonia com a natureza, preservando-a e celebrando suas tradições ancestrais. São reservados em relação a estranhos, valorizando a sabedoria, a contemplação e a harmonia. Apesar de serem hábeis guerreiros, sua verdadeira força reside na magia, sendo dotados de uma conexão única com a energia cósmica. A rixa histórica com os anões é alimentada pela diferença de visão em relação à tecnologia, sendo os elfos avessos a qualquer interferência que perturbe a natureza.";
const bokk_bharazText := "A religião dos Anões é centrada na adoração de um poderoso deus criador e no culto aos seus antepassados ilustres, que são reverenciados como figuras dignas de orgulho e louvor. Entre esses ancestrais estão Galgrumir, o primeiro anão, Killi, conhecida como a mãe da agricultura e da cerveja, Thorgrim, famoso por suas habilidades na marcenaria, e outros.
No jogo, os jogadores devem adotar uma postura respeitosa em relação à religião Anã, mostrando devoção ao deus criador e reconhecendo a importância dos antepassados em suas vidas. Isso pode se refletir em ações como oferecer orações aos deuses antes de empreender aventuras ou buscar a orientação dos ancestrais em momentos de dificuldade.
Além disso, os jogadores podem incorporar aspectos da cultura Anã em seus comportamentos in-game, como valorizar o trabalho árduo e a habilidade na forja, respeitar as tradições e costumes ancestrais, e demonstrar lealdade aos seus companheiros de equipe. Cantarolar antigas músicas Anãs ou entoar cânticos em honra aos deuses também pode contribuir para a imersão na religião e cultura Anãs dentro do jogo.";
const eluithorthText := "Respeito ao sacrifício: Demonstre valorizar a ideia de sacrificar interesses pessoais pelo bem da comunidade.
Foco no bem coletivo: Busque soluções que beneficiem não só você, mas também seu grupo ou comunidade.
Entendimento da dualidade: Reconheça que a alegria está intrinsecamente ligada à tristeza, e explore como os momentos difíceis podem levar ao crescimento.
Aceitação do destino: Encare os desafios com resignação, confiando que seus sacrifícios contribuirão para um propósito maior.
Devoção à deusa Idrith: Mostre reverência pela deusa através de orações, rituais ou seguindo os princípios éticos associados a ela.
Ao adotar esses princípios em sua interpretação, você mergulhará mais profundamente na cultura e religião dos Drows, tornando sua experiência de jogo mais rica e imersiva.";
const halleuadText := "Os Björske são um povo tradicional do norte do continente de Eora, conhecidos por sua pele alva e cabelos que variam do preto ao loiro e ruivo. São orgulhosos, valentes e generosos, transmitindo suas tradições oralmente, reunindo-se em torno de fogueiras para cultuar seus deuses com danças, carne de caça e hidromel.";	
const kaiText := "A religião dos povos do Leste, conhecida como Kai, está profundamente ligada à história e à cultura desses povos. Ela gira em torno do culto ao Deus Dragão, Huangxu, que é visto como o mensageiro divino no plano terreno através do Imperador.
Para preservar a imersão in-game e compreender melhor essa religião, sugira ao jogador que siga estas diretrizes:
Lealdade absoluta ao Imperador: Enfatize a importância da lealdade ao Imperador, visto como o portador do Mandato dos Céus concedido pelo Deus Dragão. Isso pode se manifestar através do respeito às ordens e decretos imperiais.
Respeito aos ensinamentos do Kai: Valorize os ensinamentos do Kai, que enfatizam a lealdade, a sabedoria e o conhecimento. O jogador pode demonstrar isso através de sua conduta, buscando sempre agir de acordo com os princípios éticos e morais da religião.
Honra e tradição: Destaque a importância da honra e da tradição na religião Kai. Os jogadores podem incorporar isso em seus personagens através de seus códigos de ética e conduta, como o respeito aos mais velhos e a valorização da palavra dada.
Participação nas práticas religiosas: Encoraje o jogador a participar das práticas religiosas do Kai, como cerimônias de adoração ao Deus Dragão ou rituais de passagem, como a confecção da tatuagem do dragão para os monges.";
const ushkrarText := "Em um mundo árido e implacável, os orcs se erguem como guerreiros de uma fé singular, moldada pelas vastas extensões do Deserto da Perdição. No coração dessas terras hostis, onde a areia dança ao ritmo dos ventos e a água é tão escassa quanto a esperança, os orcs encontraram sua fé no Grunntam, o Único Caminho.
No centro dessa crença está Adar Kor Doom, uma entidade mítica que personifica o deserto e seus elementos fundamentais: areia, água e sangue. Para os orcs, o deserto não é apenas um lugar, mas uma divindade que dita suas vidas e desafios.
Imagine-se diante de um altar rudimentar erguido nas dunas, onde crânios de criaturas aberrantes são ofertados como sacrifício. Sob o sol escaldante, um xamã entoa cânticos ancestrais, evocando a benção de Adar Kor Doom sobre sua tribo. Cada palavra ressoa como um eco das antigas tradições, uma reverência à natureza brutal e indomável do deserto.
E assim, os orcs caçam as temíveis Aklats, não apenas como uma questão de sobrevivência, mas como um ato sagrado de purificação. Cada criatura abatida é um tributo ao ciclo eterno de vida e morte, uma contribuição para a fertilidade das areias estéreis.
Nos períodos de chuva, quando o deserto se transforma em um oásis temporário, os orcs celebram com rituais de êxtase e indulgência. Longe das batalhas e caçadas, eles se entregam ao prazer e à comunhão, honrando a dádiva da água que sustenta sua existência.
Porém, mesmo em meio à brutalidade de sua fé, os orcs têm seus guardiões espirituais. Os Xamãs, sábios e misteriosos, são os intérpretes dos desígnios de Adar Kor Doom. Eles conduzem seus seguidores através dos caminhos áridos do deserto, guiando-os na busca pela força e sabedoria necessárias para enfrentar os desafios do Grunntam.
Neste mundo implacável e repleto de perigos, a fé dos orcs é uma luz que brilha no horizonte, uma âncora em meio à tempestade de areia. E enquanto as dunas se movem e os ventos uivam, os filhos do Deserto da Perdição permanecem firmes em sua devoção ao Grunntam, prontos para enfrentar qualquer desafio que o destino lhes reserve.";

const storyModeText := "No modo estória, o personagem não pode ser morto e nem matar outros jogadore, ou seja, cortar a cabeça.
- Ao tentar furtar outro jogador, caso tenha sucesso, receberá moedas aleatórias baseado no PP. As falhas continuam normal.
- Caso outro jogador, mesmo que seja modo verdadeiro, tente furtar você, ele receberá moedas aleatórias baseado no PP. As falhas continuam normal.
- Você ainda pode perder seu personagem caso reduza seus DPs para menos que 1
- Seu rate de UP é normal";

const trueModeText := "No modo verdadeiro, o personagem pode ser morto e pode matar outros jogadores, ou seja, cortar a cabeça.
- Poderá furtar e ser furtado normalmente.
- Não pode reclamar que foi morto por outro jogador caso tenha sido dentro do RP. Se você escolheu conflito, você aceitou as consequências.
- Seu rate de UP é maior";

const AIGLA_ID := 0x9E7;
const ALURIEL_ID := 0x9E8;
const BADURAN_ID := 0x9E9;
const BJORSKA_ID := 0x9EA;
const GULTHRAK_ID := 0x9EB;
const HAROLOTH_ID := 0x9EC;
const POLKINEA_ID := 0x9ED;
const LESTE_ID := 0x9EE;

const BOKK_BHARAZ := 0x9EF;
const ELUITHORTH := 0x9F0;
const HALLEUAD := 0x9F1;
const KAI := 0x9F2;
const LORE := 0x9F3;
const USHKRAR := 0x9F4;
const VENERATIO := 0x9F5;

var CULTURA := struct{AIGLANA := "Aiglana", HAROLOTH := "Har'oloth", LESTE := "Povos do Leste", BJORSKA := "Björska", ALURIEL := "Alüriel", BADURAN := "Badûran", GULTHRAK := "Gulthrak", POLKINEA := "Polkinea"};
var RACA := struct{ANAO := "Anão", DROW := "Drow", ELFO := "Elfo", ORC := "Orc", HUMANO :="Humano", POLSKI := "Polski"};
var BACKGROUNDS := struct{DOMESTIC_WORK := "Mestre do Lar", METAL_WORK := "Ferreiro aprendiz", GATHERING := "Coletor", PICK_POCKETING := "Rato de rua", MECHANICAL_APITUDE := "Aventureiro", HANDLE_ANIMAL := "Domador de Feras", SURVIVAL := "Caçador", MEDICINE := "Curandeiro itinerante", WOOD_WORK := "Marceneiro"};
var CULTURAL_BACKGROUNDS := struct{ "Aiglana" := "Legionário", "Har'oloth" := "Véu de Idrith", "Polkinea" := "Pés Leves", "Alüriel" := "Templo da Mente", "Björska" := "Escaramuçador", "Gulthrak" := "Brutamontes", "Badûran" := "Filho da Montanha", "Povos do Leste" := "Andarilho"};
var RELIGIAO := struct{VENERATIO := "Veneratio", ELUITHORTH := "Eluith'orth", KAI := "Kai", HALLEUAD := "Halleuad", LORE := "Lórё", BOKK_BHARAZ := "Bokk Bharaz", USHKRAR := "Ushkr'ar"};

function getCultureByPictureId(culture_id)
    case (culture_id)
        AIGLA_ID:
            return CULTURA.AIGLANA;
        ALURIEL_ID:
            return CULTURA.ALURIEL;
        BADURAN_ID:
            return CULTURA.BADURAN;
        BJORSKA_ID:
            return CULTURA.BJORSKA;
        GULTHRAK_ID:
            return CULTURA.GULTHRAK;
        HAROLOTH_ID:
            return CULTURA.HAROLOTH;
        POLKINEA_ID:
            return CULTURA.POLKINEA;
        LESTE_ID:
            return CULTURA.LESTE;
    endcase
endfunction

function getCraftCultureByPictureId(culture_id)
    case (culture_id)
        AIGLA_ID:
            return "Aiglana";
        ALURIEL_ID:
            return "Aluriel";
        BADURAN_ID:
            return "Baduran";
        BJORSKA_ID:
            return "Bjorska";
        GULTHRAK_ID:
            return "Gulthrak";
        HAROLOTH_ID:
            return "Haroloth";
        POLKINEA_ID:
            return "Polkinea";
        LESTE_ID:
            return "Leste";
    endcase
endfunction

function CultureGump(who, culture_pic)
    var next_btn := array{"9903", "9904"};
    var prev_btn := array{"9909", "9910"};

    var gump := GFCreateGump();
    GFClosable(gump, 0);
    GFGumpPic(gump, 17, 31, 0x9E6);

    GFHTMLArea(gump, 346, 56, 192, 40, "<BASEFONT Size=55 Color=#999999 >Escolha sua cultura", 0, 0); //shadow
    GFHTMLArea(gump, 345, 55, 192, 40, "<BASEFONT Size=55 Color=#ffffff >Escolha sua cultura", 0, 0);
    var x := 63;
    var y := 100;
    var i := 0;

    GFHTMLArea(gump, 100, 550, 650, 120, getCulturalDescriptionByPictureId(culture_pic), 1, 1);
    GFAddButton(gump, 543, 300, next_btn[1], next_btn[2], GF_CLOSE_BTN, 201);
    GFAddButton(gump, 273, 300, prev_btn[1], prev_btn[2], GF_CLOSE_BTN, 210);
    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);

    GFGumpPic(gump, 298, 100, culture_pic);

    return GFSendGump(who, gump);
endfunction

function getCulturalDescriptionByPictureId(culture_id)
    case (culture_id)
        AIGLA_ID:
            return aiglaText;
        ALURIEL_ID:
            return alurielText;
        BADURAN_ID:
            return baduranText;
        BJORSKA_ID:
            return bjorskaText;
        GULTHRAK_ID:
            return gulthrakText;
        HAROLOTH_ID:
            return harolothText;
        POLKINEA_ID:
            return polkineaText;
        LESTE_ID:
            return lesteText;
    endcase
endfunction

function EpicRaceGump(who, culture_pic)
    var races := getRaceByCulturalId(culture_pic);
    var gump := GFCreateGump();
    GFClosable(gump, 0);

    var x := 63;
    var y := 100;
    var i := 1;
    showPreviousGumpInformation(gump, who, culture_pic, x, y);
    var raceText := "Escolha sua raça";
    if (races.size() == 1)
        raceText := "Raça selecionada";
    endif
    GFHTMLArea(gump, x+21, y-24, 192, 40, "<BASEFONT Size=55 Color=#999999 > "+raceText, 0, 0); //shadow
    GFHTMLArea(gump, x+20, y-25, 192, 40, "<BASEFONT Size=55 Color=#ffffff > "+raceText, 0, 0);
    

    foreach race in races
        var color := "#000000";
        GFHTMLArea(gump, x, y, 192, 24, "<BASEFONT color=#{}>{}".format(color, race), 1, 0);
        if (races.size() > 1)
            GFRadioButton(gump, x+201, y, 0x9C4E, 0x9C4F, 0, 200+i);
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);
    GFGumpPic(gump, 298, 100, culture_pic);

    return GFSendGump(who, gump);
endfunction

function getRaceByCulturalId(culture_pic)
    var races;
    case (culture_pic)
        HAROLOTH_ID:
            races := {RACA.DROW};
        ALURIEL_ID:
            races := {RACA.ELFO};
        POLKINEA_ID:
            races := {RACA.POLSKI};
        GULTHRAK_ID:
            races := {RACA.ORC};
        BADURAN_ID:
            races := {RACA.ANAO};
        BJORSKA_ID:
            races := {RACA.HUMANO};
        default:
            races := array{RACA.ANAO, RACA.DROW, RACA.ELFO, RACA.HUMANO, RACA.ORC, RACA.POLSKI};
    endcase
    return races;
endfunction

function ClassGump(who, culture_pic)
    var gump := GFCreateGump();
    GFClosable(gump, 0);

    var x := 63;
    var y := 100;
    var i := 1;

    showPreviousGumpInformation(gump, who, culture_pic, x, y);

    GFHTMLArea(gump, x+16, y+40, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha seu caminho", 0, 0); //shadow
    GFHTMLArea(gump, x+15, y+39, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha seu caminho", 0, 0);

    var all_classes := array{ 
        "Caminho das Armas",
		"Caminho do Subterfúgio",
		"Caminho da Sabedoria"
    };
    foreach class in (all_classes)
        GFHTMLArea(gump, x, y+65, 192, 24, "<BASEFONT color=#000000>{}".format(class), 1, 0);
        GFRadioButton(gump, x+201, y+65, 0x9C4E, 0x9C4F, 0, 200+i);

        sleepms(2);
        y += 26;
        i++;
    endforeach

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);
    GFGumpPic(gump, 298, 100, culture_pic);

    return GFSendGump(who, gump);
endfunction

function backgroundGump(who, culture_pic)
    var gump := GFCreateGump();
    GFClosable(gump, 0);

    var x := 63;
    var y := 100;
    var i := 1;

    showPreviousGumpInformation(gump, who, culture_pic, x, y);

    GFHTMLArea(gump, x+16, y+96, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha seu passado", 0, 0); //shadow
    GFHTMLArea(gump, x+15, y+95, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha seu passado", 0, 0);

    var all_backgrounds := BACKGROUNDS;
    VAR cultural_bg := backgroundByCulture(who);
    var cfg := ReadConfigFile(":charactercreation:config/backgrounds");
    foreach bg in (all_backgrounds)
        GFHTMLArea(gump, x, y+116, 192, 24, "<BASEFONT color=#ffffff>{}".format(bg), 1, 0);
        GFToolTipText(gump, cfg[bg].Desc);
        GFRadioButton(gump, x+201, y+116, 0x9C4E, 0x9C4F, 0, 200+i);
        sleepms(2);
        y += 26;
        i++;
    endforeach
    GFHTMLArea(gump, x, y+116, 192, 24, "<BASEFONT color=#ffffff>{}".format(cultural_bg), 1, 0);
    GFToolTipText(gump, cfg[cultural_bg].Desc);

    GFRadioButton(gump, x+201, y+116, 0x9C4E, 0x9C4F, 0, 200+i);

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);


    return GFSendGump(who, gump);
endfunction

function backgroundByCulture(who)
    var chardata := GetObjProperty(who, "chardata");
    var culture := chardata.culture;

    return CULTURAL_BACKGROUNDS[culture];
endfunction

function traitGump(who, culture_pic, traits)
    var gump := GFCreateGump();
    GFClosable(gump, 0);

    var x := 63;
    var y := 100;
    var i := 1;

    showPreviousGumpInformation(gump, who, culture_pic, x, y);

    GFHTMLArea(gump, x+21, y+136, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha sua Característica", 0, 0); //shadow
    GFHTMLArea(gump, x+20, y+135, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha sua Característica", 0, 0);

	foreach trait in traits
        var trait_name := trait.nome;
        var trait_desc := trait.desc;
        var trait_adv := trait.Vantagens;
        
        GFHTMLArea(gump, x, y+151, 192, 24, "<BASEFONT color=#ffffff >{}".format(trait_name), 1, 0);
        GFTooltipText(gump, "{}<br><BASEFONT color=#ffffff>".format(trait_desc));
        GFTooltipText(gump, "{}<br><BASEFONT color=#ffffff>".format(trait_adv));
        GFRadioButton(gump, x+201, y+151, 0x9C4E, 0x9C4F, 0, 200+i);
        sleepms(2);
        y += 26;
        i++;
	endforeach

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);

    return GFSendGump(who, gump);
endfunction

function GetSkillValueDesc(skill)

	if (!skill || skill == error)
		return "";
	elseif (skill == 1)
		return "Terciária";
	elseif (skill == 2)
		return "Secundária";
	elseif (skill == 3)
		return "Primária";
	endif

endfunction

function listTraits(who, chardata)

	var cfg := ReadConfigFile(":charactercreation:config/traits");
	var keys := GetConfigStringKeys( cfg );

	var traits := array;
	var selectedtrait := 1;
	foreach key in keys
		var elem  := FindConfigElem(cfg, key);
		var canadd := 1;
		var racas := GetConfigStringArray( elem, "Raca" );
		var culturas := GetConfigStringArray( elem, "Cultura" );
		var classes := GetConfigStringArray( elem, "Classe" );

		if ((racas.size() >= 1) && !(chardata.raca in racas))
			canadd := 0;
		endif
		if ((classes.size()>=1) && !(chardata.classe in classes))
			canadd := 0;
		endif
		if ((culturas.size() >= 1) && !(chardata.culture in culturas))
			canadd := 0;
		endif

		if (canadd)
			var trait  := struct;
			trait.+nome := GetconfigString(elem, "Nome");
			trait.+desc := GetconfigString(elem, "Desc");
			trait.+vantagens := GetConfigString( elem, "Vantagens" );
			trait.+desvantagens := GetConfigString( elem, "Desvantagens" );
			traits.append(trait);
		endif
	endforeach

    return traits;
endfunction

function showPreviousGumpInformation(byref gump, who, culture_pic := 0, x, y)
    GFGumpPic(gump, 17, 31, 0x9E6);

    var chardata := GetObjProperty(who, "chardata");
    chardata.+Primarias;
    var race := chardata.raca;
    var color := "#FFD700";
    var class := chardata.classe;
    var bg := chardata.background;
    var trait := chardata.trait;
    var skills := chardata.Skills;
    if (race)
        GFHTMLArea(gump, x+86, y-24, 192, 40, "<BASEFONT Size=55 Color=#999999 > Raça", 0, 0); //shadow
        GFHTMLArea(gump, x+85, y-25, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Raça", 0, 0);
        GFHTMLArea(gump, x+16, y, 192, 24, "<BASEFONT color=#{}>{}".format(color, race), 1, 0);
    endif

    if (culture_pic)
        GFHTMLArea(gump, 346, 66, 192, 40, "<BASEFONT Size=55 Color=#999999 > Cultura selecionada", 0, 0); //shadow
        GFHTMLArea(gump, 345, 65, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Cultura selecionada", 0, 0);
        GFGumpPic(gump, 298, 100, culture_pic);
    endif

    if (class)
        GFHTMLArea(gump, x+81, y+29, 192, 40, "<BASEFONT Size=55 Color=#999999 > Classe", 0, 0); //shadow
        GFHTMLArea(gump, x+80, y+30, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Classe", 0, 0);
        GFHTMLArea(gump, x+16, y+51, 192, 24, "<BASEFONT color=#{}>{}".format(color, class), 1, 0);
    endif

    if (bg)
        GFHTMLArea(gump, x+81, y+82, 192, 40, "<BASEFONT Size=55 Color=#999999 > Passado", 0, 0); //shadow
        GFHTMLArea(gump, x+80, y+81, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Passado", 0, 0);
        GFHTMLArea(gump, x+16, y+101, 192, 24, "<BASEFONT color=#{}>{}".format(color, bg), 1, 0);
    endif

    if (trait)
        GFHTMLArea(gump, x+61, y+132, 192, 40, "<BASEFONT Size=55 Color=#999999 > Característica", 0, 0); //shadow
        GFHTMLArea(gump, x+60, y+131, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Característica", 0, 0);
        GFHTMLArea(gump, x+16, y+151, 192, 24, "<BASEFONT color=#{}>{}".format(color, trait), 1, 0);
    endif

if (GetObjProperty(who, "skill") == 1)
    GFHTMLArea(gump, x+81, y+182, 192, 40, "<BASEFONT Size=55 Color=#999999 > Skills", 0, 0); //shadow
    GFHTMLArea(gump, x+80, y+181, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Skills", 0, 0);

    foreach skill in (skills.keys())
        var color := "";
        if (skills[skill] == 3)
            color := "0000CC";
        elseif (skills[skill] == 2)
            color := "007A23";
        elseif (skills[skill] == 1)
            color := "FFE700";
        endif

        GFHTMLArea(gump, x+16, y+201, 192, 24, "<BASEFONT color=#{}>{} | {}".format(color, skill, GetSkillValueDesc(skills[skill])), 1, 0); //shadow
        y += 30;
    endforeach
endif
    
endfunction

function skillGump(who, culture_pic, byref chardata)
    var gump := GFCreateGump();
    GFClosable(gump, 0);
    var minus_btn := {0x9F7, 0x9F8};
    var plus_btn := {0x9F9, 0x9FA};
    var pri_allowed := howManyPrimarias(chardata);

    var x := 63;
    var y := 100;
    var i := 1;
    showPreviousGumpInformation(gump, who, culture_pic, x, y);
    x := 555;
    y := 100;
    GFHTMLArea(gump, x+1, y-24, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha suas skills", 0, 0); //shadow
    GFHTMLArea(gump, x, y-25, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha suas skills", 0, 0);
    var cfg;
    var elem;

    cfg := ReadConfigFile(":charactercreation:config/classes");
    elem := FindConfigElem(cfg, cstr(chardata.classe));
    var primarias    := GetConfigStringArray(elem, "P");
    var secundarias  := GetConfigStringArray(elem, "S");
    var terciarias   := GetConfigStringArray(elem, "T");
    var quaternarias := GetConfigStringArray(elem, "Q");
    var value := 1;
    var btn_value;
    x+=10;
    for (i := 1; i <= primarias.size()+2; i++)
        var skill := primarias[i];
        btn_value := GetSkillIdFromName(skill);
        if (i == primarias.size()+1)
            if (chardata.bgBonus in primarias)
                i++;
                break;
            endif
            skill := chardata.bgBonus;
            btn_value := GetSkillIdFromName(skill);
            // if (chardata.bgBonus2)
            //     i -= 1;
            //     skill := chardata.bgBonus2;
            //     chardata.Erase("bgBonus2");
            // endif
         endif
        if (i == primarias.size()+2 && chardata.bgBonus2)
            if (chardata.bgBonus2 in primarias)
                i++;
                break;
            endif
            skill := chardata.bgBonus2;
            btn_value := GetSkillIdFromName(skill);
        endif
        if (skill == error)
            continue;
        endif
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#0000CC >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 100+btn_value);
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 130+btn_value);
        endif
        sleepms(2);
        y += 26;
    endfor
    y+=10;
    value := 2;
    foreach skill in secundarias
        if (skill == chardata.bgBonus)
            continue;
        endif

        btn_value := GetSkillIdFromName(skill);
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#007A23 >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 200+btn_value);
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 230+btn_value);
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach
    y+=10;
    value := 3;
    foreach skill in terciarias
        if (skill == chardata.bgBonus)
            continue;
        endif

        btn_value := GetSkillIdFromName(skill);
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#FFE700 >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 300+btn_value);
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 330+btn_value);
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach
    y+=10;
    value := 4;
    foreach skill in quaternarias
        if (skill == chardata.bgBonus)
            continue;
        endif
        if (chardata.background == "Filho da Montanha" && skill == METALWORKING )
            continue;
        endif

        btn_value := GetSkillIdFromName(skill);
        GFHTMLArea(gump, x, y-4, 135, 24, "<BASEFONT color=#CC0000 >{}".format(skill), 1, 0);
        if (chardata.Skills[skill] >= 1)
            GFAddButton(gump, x+138, y-2, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 400+btn_value);
        endif
        if ((chardata.points - value >= 0) && (chardata.Skills[skill] < 3) && ((chardata.Primarias < pri_allowed) || (chardata.Skills[skill] < 2 && chardata.points - value >= 0))) 
            GFAddButton(gump, x+158, y-2, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 430+btn_value);
        endif
        sleepms(2);
        y += 26;
        i++;
    endforeach
    var count := 0;
    var skills := chardata.Skills;
    y := 300;
    x := 73;
    var color := "FFFFFF";
    chardata.Primarias := 0;
    foreach skill in (skills.keys())
        if (skills[skill] == 3)
            chardata.Primarias++;
            color := "0000CC";
        elseif (skills[skill] == 2)
            color := "007A23";
        elseif (skills[skill] == 1)
            color := "FFE700";
        endif
        if (skills[skill] > 0)
            GFHTMLArea(gump, x, y, 192, 24, "<BASEFONT color=#{}>{} | {}".format(color, skill, GetSkillValueDesc(skills[skill])), 1, 0); //shadow
            y+=30;
        endif
    endforeach
    
    SetObjProperty(who, "chardata", chardata);
    GFHTMLArea(gump, 345, 515, 192, 40, "<BASEFONT Size=55 Color=#999999 > Pontos restantes", 0, 0);
    GFHTMLArea(gump, 346, 516, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Pontos restantes", 0, 0); //shadow
    GFHTMLArea(gump, 400, 536, 35, 20, "<BASEFONT color=#FFE700 >{}".format(chardata.points), 1, 0);

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 500); // Botão de fechar

    return GFSendGump(who, gump);
endfunction

function howManyPrimarias(chardata)
    if (chardata.trait == "Sabe-Tudo")
        return 1;
    endif

    return 2;
endfunction

function culturalTraitBonus(who, byref chardata)
    var culturalBg := chardata.background;
    if (culturalBg == "Legionário")
        return chardata.+bgBonus := PARRY;
    elseif (culturalBg == "Véu de Idrith")
        return chardata.+bgBonus := AWARENESS;
    elseif (culturalBg == "Pés Leves")
        return chardata.+bgBonus := SNEAK;
    elseif (culturalBg == "Templo da Mente")
        return chardata.+bgBonus := MAGICLORE;
    elseif (culturalBg == "Escaramuçador")
        return chardata.+bgBonus := RANGEDCOMBAT;
    elseif (culturalBg == "Brutamontes")
        return chardata.+bgBonus := TACTICS;
    elseif (culturalBg == "Filho da Montanha")
        return chardata.+bgBonus := GATHERING;
    elseif (culturalBg == "Andarilho")
        return chardata.+bgBonus := MELEECOMBAT1H;
    endif
endfunction

function attributeGump(who, culture_pic, byref chardata)
    var gump := GFCreateGump();
    GFClosable(gump, 0);
    var x := 63;
    var y := 100;
    var i := 1;
    var minus_btn := {0x9F7, 0x9F8};
    var plus_btn := {0x9F9, 0x9FA};
    var cost := 5;
    showPreviousGumpInformation(gump, who, culture_pic, x, y);
    GFHTMLArea(gump, 555, y, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha seus atributos", 0, 0); //shadow
    GFHTMLArea(gump, 556, y, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Escolha seus atributos", 0, 0);

    GFHTMLArea(gump, 555, y+20, 120, 25, "<BASEFONT color=#FFFFFF >Forca:    {}".format(chardata.str), 1, 0);
    if (chardata.str > 40)
        GFAddButton(gump, 675, y+25, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 201);
    endif
    if ((chardata.attribute_points - cost >= 0) && (chardata.str <100)) 
        GFAddButton(gump, 695, y+25, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 200);
    endif

    GFHTMLArea(gump, 555, y+40, 120, 25, "<BASEFONT color=#FFFFFF >Destreza:  {}".format(chardata.dex), 1, 0);
    if (chardata.dex > 40)
        GFAddButton(gump, 675, y+45, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 211);
    endif
    if ((chardata.attribute_points - cost >= 0) && (chardata.dex <100)) 
        GFAddButton(gump, 695, y+45, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 210);
    endif

    GFHTMLArea(gump, 555, y+60, 120, 25, "<BASEFONT color=#FFFFFF >Inteligencia: {}".format(chardata.int), 1, 0);
    if (chardata.int > 40)
        GFAddButton(gump, 675, y+65, minus_btn[1], minus_btn[2], GF_CLOSE_BTN, 221);
    endif
    if ((chardata.attribute_points - cost >= 0) && (chardata.int <100)) 
        GFAddButton(gump, 695, y+65, plus_btn[1], plus_btn[2], GF_CLOSE_BTN, 220);
    endif

    GFHTMLArea(gump, 345, 515, 192, 40, "<BASEFONT Size=55 Color=#999999 > Pontos restantes", 0, 0);
    GFHTMLArea(gump, 346, 516, 192, 40, "<BASEFONT Size=55 Color=#ffffff > Pontos restantes", 0, 0); //shadow
    GFHTMLArea(gump, 400, 536, 35, 20, "<BASEFONT color=#FFE700 >{}".format(chardata.attribute_points), 1, 0);

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 500); // Botão de fechar

    return GFSendGump(who, gump);
endfunction

function ReligionGump(who, religion_pic)
    var next_btn := array{"9903", "9904"};
    var prev_btn := array{"9909", "9910"};

    var gump := GFCreateGump();
    GFClosable(gump, 0);
    GFGumpPic(gump, 17, 31, 0x9E6);

    GFHTMLArea(gump, 346, 56, 192, 40, "<BASEFONT Size=55 Color=#999999 >Escolha sua religião", 0, 0); //shadow
    GFHTMLArea(gump, 345, 55, 192, 40, "<BASEFONT Size=55 Color=#ffffff >Escolha sua religião", 0, 0);
    var x := 63;
    var y := 100;
    var i := 0;

    GFHTMLArea(gump, 100, 550, 650, 120, getReligionDescriptionByPictureId(religion_pic), 1, 1);
    GFAddButton(gump, 543, 300, next_btn[1], next_btn[2], GF_CLOSE_BTN, 201);
    GFAddButton(gump, 273, 300, prev_btn[1], prev_btn[2], GF_CLOSE_BTN, 210);
    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 500);

    GFGumpPic(gump, 298, 100, religion_pic);

    return GFSendGump(who, gump);
endfunction

function getReligionByPictureId(religion_id)
    case (religion_id)
        VENERATIO:
            return RELIGIAO.VENERATIO;
        LORE:
            return RELIGIAO.LORE;
        BOKK_BHARAZ:
            return RELIGIAO.BOKK_BHARAZ;
        HALLEUAD:
            return RELIGIAO.HALLEUAD;
        KAI:
            return RELIGIAO.KAI;
        ELUITHORTH:
            return RELIGIAO.ELUITHORTH;
        USHKRAR:
            return RELIGIAO.USHKRAR;
    endcase
endfunction

function getReligionDescriptionByPictureId(culture_id)
    case (culture_id)
        VENERATIO:
            return veneratioText;
        LORE:
            return loreText;
        BOKK_BHARAZ:
            return bokk_bharazText;
        HALLEUAD:
            return halleuadText;
        KAI:
            return kaiText;
        ELUITHORTH:
            return eluithorthText;
        USHKRAR:
            return ushkrarText;
    endcase
endfunction

function itemInheritance(who)
var chardata := GetObjProperty(who, "chardata");

genericItems(who);
armorsByCulture(who);
weaponsByClassAndCulture(who);
workingItems(who);
endfunction


function genericItems(who)
    var chardata := GetObjProperty(who, "chardata");
    var skills := chardata.Skills;

    CreateItemInBackpack(who, 0x0F52, 1); // Adaga
    CreateItemInBackpack(who, 0x1F03, 1); // Roupa
	CreateItemInBackpack(who, 0xba63, 100); //moedas de cobre
    CreateItemInBackpack(who, 0x170D, 1); // Sandals
    CreateItemInBackpack(who, 0x0F60, 1); // longsword
    CreateItemInBackpack(who, 0x152e, 1); // short pants
    CreateItemInBackpack(who, 0x1517, 1); // shirt
    CreateItemInBackpack(who, 3940, 1); // torch
endfunction

function weaponsByClassAndCulture(who)
    var chardata := GetObjProperty(who, "chardata");
    var skills := chardata.Skills;

    if (chardata.culture == CULTURA.GULTHRAK)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x26C6, 1); // scepter
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B78, 1); // shield
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x0F4E, 1); // bardiche
        endif
    endif

    if (chardata.culture == CULTURA.AIGLANA)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x27EF, 1); // espada curta
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B76, 1); // Torre
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x1402, 1); // short spear
        endif
    endif

    if (chardata.culture == CULTURA.HAROLOTH)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x1401, 1); //kryss
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B73, 1); // buckler
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x26CB, 1); //crescent
        endif
    endif

    if (chardata.culture == CULTURA.POLKINEA)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x1440, 1); //cutlass
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B73, 1); // buckler
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x0e87, 1); //crescent
        endif
    endif

    if (chardata.culture == CULTURA.BJORSKA)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x0f63, 1); // long spear
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B7A, 1); // wooden shield
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x0f49, 1); // axe
        endif
    endif

    if (chardata.culture == CULTURA.LESTE)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x13fe, 1); // wakizashi
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B72, 1); // round shield
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x27A2, 1); // Katana
        endif
    endif

    if (chardata.culture == CULTURA.BADURAN)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x143c, 1); // HAMMERPICK
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B74, 1); // Kite shield 
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x1438, 1); // warhammer
        endif
    endif

    if (chardata.culture == CULTURA.ALURIEL)
        if (skills[MELEECOMBAT1H] >= 1)
            CreateItemInBackpack(who, 0x0f5f, 1); // rapiera
        endif
        if (skills[PARRY] >= 1)
            CreateItemInBackpack(who, 0x1B73, 1); // buckler
        endif
        if (skills[MELEECOMBAT2H ] >= 1)
            CreateItemInBackpack(who, 0x26CB, 1); // crescent
        endif
        if (skills[RANGEDCOMBAT] >= 1)
        endif
    endif

    if (skills[RANGEDCOMBAT] >= 1)
        var ammo_amount := skills[RANGEDCOMBAT] * 80;
        if (chardata.culture == CULTURA.ALURIEL)
            CreateItemInBackpack(who, 0x26CC, 1); // longbow
            CreateItemInBackpack(who, 0xf3f, ammo_amount); // arrows
        elseif (chardata.culture == CULTURA.BADURAN)
            CreateItemInBackpack(who, 0x0f4f, 1); // crossbow
            CreateItemInBackpack(who, 0x1bfb, ammo_amount); // bolts
        else
            CreateItemInBackpack(who, 0x13B2, 1); // bow
            CreateItemInBackpack(who, 0xf3f, ammo_amount); // arrows
        endif
    endif

    CreateItemInBackpack(who, 0x2fb7, 1); // aljava
endfunction

function armorsByCulture(who)
    var chardata := GetObjProperty(who, "chardata");

    if (chardata.culture == CULTURA.GULTHRAK)
        CreateItemInBackpack(who, 0x144e, 1); // Armadura de ossos
        CreateItemInBackpack(who, 0x144f, 1); // Armadura de ossos
        CreateItemInBackpack(who, 0x1450, 1); // Armadura de ossos
        CreateItemInBackpack(who, 0x1451, 1); // Armadura de ossos
        CreateItemInBackpack(who, 0x1452, 1); // Armadura de ossos
    endif

    if (chardata.culture == CULTURA.BADURAN)
        CreateItemInBackpack(who, 0x13ec, 1); // Armadura de aneis
        CreateItemInBackpack(who, 0x13ee, 1); // Armadura de aneis
        CreateItemInBackpack(who, 0x13f0, 1); // Armadura de aneis
        CreateItemInBackpack(who, 0x13f2, 1); // Armadura de aneis
    endif

    if (chardata.culture == CULTURA.AIGLANOS)
        CreateItemInBackpack(who, 0x13BE, 1); // Lorica Segmentata
        CreateItemInBackpack(who, 0x13BF, 1); // Lorica Segmentata
        CreateItemInBackpack(who, 0x13C0, 1); // Lorica Segmentata
        CreateItemInBackpack(who, 0x13C1, 1); // Lorica Segmentata
        CreateItemInBackpack(who, 0x13C2, 1); // Lorica Segmentata
    endif

    if (chardata.culture == CULTURA.HAROLOTH)
        CreateItemInBackpack(who, 0x13D6, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13D5, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13D4, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13DA, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13DB, 1); // Studded Leather
    endif

    if (chardata.culture == CULTURA.POLKINEA)
        CreateItemInBackpack(who, 0x13C7, 1); // Armadura de couro simples
        CreateItemInBackpack(who, 0x13CD, 1); // Armadura de couro simples
        CreateItemInBackpack(who, 0x1DB9, 1); // Armadura de couro simples
        CreateItemInBackpack(who, 0x13CB, 1); // Armadura de couro simples
        CreateItemInBackpack(who, 0x13CC, 1); // Armadura de couro simples
    endif

    if (chardata.culture == CULTURA.ALURIEL)
        CreateItemInBackpack(who, 0x13D6, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13D5, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13D4, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13DA, 1); // Studded Leather
        CreateItemInBackpack(who, 0x13DB, 1); // Studded Leather
    endif

    if (chardata.culture == CULTURA.BJORSKA)
        CreateItemInBackpack(who, 0x13BB, 1); // Cota de malhas
        CreateItemInBackpack(who, 0x13BE, 1); // Cota de malhas
        CreateItemInBackpack(who, 0x13BF, 1); // Cota de malhas
    endif

    if (chardata.culture == CULTURA.LESTE)
        CreateItemInBackpack(who, 0x27c6, 1); // Armadura de fibra
        CreateItemInBackpack(who, 0x2786, 1); // Armadura de fibra
        CreateItemInBackpack(who, 0x27c9, 1); // Armadura de fibra
        CreateItemInBackpack(who, 0x277a, 1); // Armadura de fibra
    endif

endfunction

function workingItems(who)
    var chardata := GetObjProperty(who, "chardata");
    var skills := chardata.Skills;

    if (skills[WOODWORKING] >= 1)
        CreateItemInBackpack(who, 0x1035, 1); // saw
    endif
    if (skills[METALWORKING] >= 1)
        CreateItemInBackpack(who, 0x13E3, 1); // smithhammer
        CreateItemInBackpack(who, 0x5107, 1); // smelting pot
    endif
    if (skills[GATHERING] >= 1)
        CreateItemInBackpack(who, 0x0f43, 1); // hatchet
        CreateItemInBackpack(who, 0x0e85, 1); // pickaxe
    endif
    if (skills[SURVIVAL] >= 1)
        CreateItemInBackpack(who, 0x13f6, 1); // butcher knife
        CreateItemInBackpack(who, 0x0ec4, 1); // skinning knife
    endif

    if (skills[MEDICINE] >= 1)
        CreateItemInBackpack(who, 0xe21, (skills[MEDICINE] * 40)); // Bandages
    endif

    if (skills[MECHANICALAPITUDE] >= 1)
        CreateItemInBackpack(who, 0x1035, (skills[MECHANICALAPITUDE] * 8)); // lockpick
    endif

    if (skills[DomesticWork] >= 1)
        CreateItemInBackpack(who, 0x0f9d, 1); // sewingkit
    endif

    if (skills[DomesticWork] >= 1 || skills[MEDICINE] >= 1)
        CreateItemInBackpack(who, 0xf9e, 1); // Scissors
    endif

    if (skills[ALCHEMY] == 2)
		var book := createiteminbackpack(who, "alchemybook");
        book.newbie := 1;
		setobjproperty(book, "serialid", who.serial);
		setobjproperty(book, "marked",who.name + " - " + who.acctname);

        var recipes := array;
		recipes := CreateVeryBasicRecipes();
		var basic_book := createiteminbackpack(who, "alchemybook");
		setobjproperty(basic_book, "recipes", recipes);
	elseif (skills[ALCHEMY] == 3)
		var book1:= CreateItemInBackpack(who, "alchemybook");
		setobjproperty(book1, "serialid", who.serial);
		setobjproperty(book1, "marked",who.name + " - " + who.acctname);
        book1.newbie := 1;
        var recipes := array;
		recipes := CreateBasicRecipes();
		var book2 := createiteminbackpack(who, "alchemybook");
        book2.newbie := 1;
		setobjproperty(book2, "recipes", recipes);
		setobjproperty(book2, "serialid",who.serial);
		setobjproperty(book2, "marked",who.name + " - " + who.acctname);
	endif
endfunction

function attributeBonusByRaceAndTraits(who)
    var chardata := GetObjProperty(who, "chardata");

    var raca := chardata.raca;
    var final_str := chardata.str;
    var final_dex := chardata.dex;
    var final_int := chardata.int;

    if (raca == RACA.ANAO)
        final_str += 10;
    elseif (raca == RACA.ELFO)
        final_int += 10;
    elseif (raca == RACA.DROW)
        final_dex += 5;
        final_int +=5;
    elseif (raca == RACA.ORC)
        final_str += 5;
        final_int +=5;
    elseif (raca == RACA.POLSKI)
        final_dex += 10;
    endif

    if (chardata.trait == "Corpulento")
        final_int -= 5;
        final_dex -= 5;
        final_str += 20;
	elseif (chardata.trait == "Genio")
        final_str -= 5;
        final_dex -= 5;
        final_int += 20;
	elseif (chardata.trait == "Agil")
        final_str -= 5;
        final_int -= 5;
        final_dex += 20;
    elseif (chardata.trait == "Afogado em Mana")
        final_str -= 10;
        final_dex -= 10;
	elseif (chardata.trait == "Robusto")
        final_str += 25;
        final_int -= 5;
	elseif (chardata.trait == "Velho") // Parece que foi removido por alguem
        final_str -= 10;
        final_dex -= 10;
        final_int += 40;
	endif

    AP_SetTrueStat(who, STRENGTH, final_str);
    AP_SetTrueStat(who, DEXTERITY, final_dex);
    AP_SetTrueStat(who, INTELLIGENCE, final_int);
endfunction

function resetCharacter(who)
    resetGender(who);
    if (GetObjProperty(who, "skill") == 1)
        EraseObjProperty(who, "skill");
    endif
    if (GetObjProperty(who, "chardata"))
        EraseObjProperty(who, "chardata");
    endif
    if (GetObjProperty(who, "classe"))
        EraseObjProperty(who, "classe");
    endif
    if (GetObjProperty(who, "advclass"))
        EraseObjProperty(who, "advclass");
    endif
    if (GetObjProperty(who, "raca"))
        EraseObjProperty(who, "raca");
    endif

	if (who.cmdlevel < 2)
		var equiped := listequippeditems(who);
		foreach item in equiped
			if (item != who.backpack)
                DestroyItem(item);
			endif
		endforeach
		equiped := enumerateitemsincontainer(who.backpack);
		foreach item in equiped
			DestroyItem(item);
		endforeach
		equiped := 0;
	endif

	//zera as skills
	foreach attrib in AP_ListAttributesByType()
		AP_SetTrueSkill(who, attrib, 0);
		sleepms(10);
	endforeach
endfunction

function resetGender(who)
    if (who.graphic == 1828 || who.graphic == 1830 || who.graphic == 1832 || who.graphic == 1834)
        who.graphic := 400;
    elseif (who.graphic == 1829 || who.graphic == 1831 || who.graphic == 1833 || who.graphic == 1835)
        who.graphic := 401;
    endif
endfunction

function looksGump(who, chardata)
	var disfarce := struct;
    disfarce.+barba := "";
    disfarce.+cabelo := "";
    disfarce.+corcabelo := -1;
    disfarce.+corbarba := -1;
    disfarce.+corpele := -1;

    escolherCabelo(who, disfarce, chardata.raca);
    escolheCorCabelo(who, disfarce, 0, chardata.raca, 1);
    if (chardata.raca != RACA.ELFO && chardata.raca != RACA.DROW)
        escolherBarba(who, disfarce);
    endif

    SkinGump(who, disfarce, chardata.raca, 1);

    who.color := disfarce.corpele;
    who.truecolor := disfarce.corpele;

    var mybarba := GetEquipmentByLayer(who, LAYER_BEARD);
    var newbarba := CreateItemAtLocation(who.x, who.y, who.z, disfarce.barba, 1, who.realm);

    newbarba.color := 1109;

    newbarba.color := disfarce.corcabelo;
    if (mybarba)
        DestroyItem(mybarba);
    endif
    var result := EquipItem(who, newbarba);

    var myhair := GetEquipmentByLayer(who, LAYER_HAIR);
    var newhair := CreateItemAtLocation(who.x, who.y, who.z, disfarce.cabelo, 1, who.realm);

    newhair.color := 1109;

    newhair.color := disfarce.corcabelo;
    var result2 := DestroyItem(myhair);
    result := EquipItem(who, newhair);

	if (YesNo(who, "Deseja manter esta aparência?" , "Sim.", "Não."))
		return 1;
	else
		looksGump(who, chardata);
	endif
endfunction


function gameModeGump(who, religion_pic)
    var next_btn := array{"9903", "9904"};
    var prev_btn := array{"9909", "9910"};

    var gump := GFCreateGump();
    GFClosable(gump, 0);
    GFGumpPic(gump, 17, 31, 0x9E6);

    GFHTMLArea(gump, 326, 56, 192, 40, "<BASEFONT Size=55 Color=#999999 >Escolha seu modo de jogo", 0, 0); //shadow
    GFHTMLArea(gump, 325, 55, 192, 40, "<BASEFONT Size=55 Color=#ffffff >Escolha seu modo de jogo", 0, 0);
    var x := 63;
    var y := 100;
    var i := 0;

    GFHTMLArea(gump, 100, 550, 650, 120, gameModeDescriptionByPictureId(religion_pic), 1, 1);
    GFAddButton(gump, 543, 300, next_btn[1], next_btn[2], GF_CLOSE_BTN, 201);
    GFAddButton(gump, 273, 300, prev_btn[1], prev_btn[2], GF_CLOSE_BTN, 210);
    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200);

    GFGumpPic(gump, 298, 100, religion_pic);

    return GFSendGump(who, gump);
endfunction

function gameModeByPictureId(gameModeId)
    var trueMode := "True Mode";
    var storyMode := "Story Mode";
    case (gameModeId)
        0x9FC:
            return trueMode;
        0x9FB:
            return storyMode;
    endcase
endfunction

function gameModeDescriptionByPictureId(gameModeId)
    case (gameModeId)
        0x9FC:
            return trueModeText;
        0x9FB:
            return storyModeText;
    endcase
endfunction

function pathOfWisdomGump(who, culture_pic)
    var gump := GFCreateGump();
    GFClosable(gump, 0);

    var x := 63;
    var y := 100;
    var i := 1;
    showPreviousGumpInformation(gump, who, culture_pic, x, y);
    x := 555;
    y := 100;
    GFHTMLArea(gump, x+1, y-24, 192, 40, "<BASEFONT Size=55 Color=#999999 > Escolha seu caminho", 0, 0); //shadow
    GFHTMLArea(gump, x, y-25, 192, 400, "<BASEFONT Size=55 Color=#ffffff > Escolha seu caminho", 0, 0);

    var wisdomPaths := array{"Mago", "Alquimista"};
    var chardata := GetObjProperty(who, "chardata");
    var culture := chardata.culture;
    if (culture == CULTURA.GULTHRAK)
        wisdomPaths.append("Xamã");
    elseif (culture == CULTURA.BADURAN)
        wisdomPaths.append("Martelo Divino");
        wisdomPaths.append("Engenheiro");
    elseif (culture == CULTURA.AIGLANA)
        wisdomPaths.append("Augur");
    elseif (culture == CULTURA.HAROLOTH && who.graphic == 1831)
        wisdomPaths.append("Clériga de Idrith");
    endif
    foreach path in wisdomPaths
        var color := "#000000";
        GFHTMLArea(gump, x, y, 192, 24, "<BASEFONT color=#{}>{}".format(color, path), 1, 0);
        GFRadioButton(gump, x+201, y, 0x9C4E, 0x9C4F, 0, 200+i);
        sleepms(2);
        y += 26;
        i++;
    endforeach

    GFAddButton(gump, 653, 680, 4005, 4007, GF_CLOSE_BTN, 200); // Botão de fechar
    return GFSendGump(who, gump);
endfunction