//CRAFTING
const PROPNAME_TIER_COMPONENTE := "tierComponente";
const PROPNAME_ENCAIXE_COMPONENTE := "encaixeComponente";
const PROPNAME_FABRICADO := "fabricado";
const PROPNAME_FABRICADO_TRATAMENTO := "fabricadoTratamento";
const PROPNAME_MATERIAL := "material"; 
const PROPNAME_ARTIFICE_SERIAL := "crafterserial"; 
const PROPNAME_ESTACAO_FORJA := "estacaoForja"; 
const PROPNAME_ISESTACAO_OCUPADA := "isEstacaoOcupada"; 


//SISTEMA DESTRUIVEIS
const PROPNAME_DURABILIDADE := "durabItem"; 
const PROPNAME_DURABILIDADE_MAX := "maxDurabItem"; 
const PROPNAME_RESITEM_MULT := "resItem"; 
const PROPNAME_CHAVE_ORIGINAL := "serialOriginal"; 
const PROPNAME_ARMADILHAS := "TrapList"; 
const PROPNAME_DISPENSAVEL_FLAG := "isDispensavel"; 
const PROPNAME_INDESTRUTIVEL := "isIndestrutivel"; 
const PROPNAME_DESTROCO := "isDestroco"; 
const PROPNAME_DEED_SERIALS := "ItemsCreatedSerials"; 
const PROPNAME_AREA_SEGURA := "itemEmAreaSegura"; 

//CONTROLE DE GUMP

const PROPNAME_POSICAO_GUMP := "posicaoGump";