// use uo;

// function GetPointsInRadius(mid_x, mid_y, radius)
// 	var x_row := mid_x-radius;
// 	var y_col := mid_y-radius;
// 	var stop_x := mid_x+radius;
// 	var stop_y := mid_y+radius;

// 	var point_list := array();
// 	var coord := struct;
// 	coord.+x;
// 	coord.+y;

// 	for ( x_row:=(mid_x-radius); x_row<=stop_x; x_row:=x_row+1 )
// 		sleepms(2);
// 		for ( y_col:=(mid_y-radius); y_col<=stop_y; y_col:=y_col+1 )
// 			coord.x := x_row;
// 			coord.y := y_col;
// 			point_list.append(coord);
// 			sleepms(2);
// 		endfor
// 	endfor
	
// 	return point_list;
// endfunction

