name: Compile Dev Scripts

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Compile scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Compilação no servidor
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd epic-shard-dev
            git checkout develop
            git pull
            ./compilar.sh
            systemctl restart pol-dev
